### PR TITLE
Add configuration for building Debian packages.

### PR DESCRIPTION
**Pull request by BarbarossaTM**
Create a pristine build dir

    mkdir /tmp/ah-build

  Create a tarball for the latest stable version

    git archive --format tar --prefix=anycast-healthchecker-0.8.1/ HEAD | xz > /tmp/ah-build/anycast-healthchecker_0.8.1.orig.tar.xz

  Extract the tarball and change into the build directory

    cd /tmp/ah-build && tar xf anycast-healthchecker_0.8.1.orig.tar.xz && cd anycast-healthchecker-0.8.1

  Build the package

   dpkg-buildpackage -uc -us -rfakeroot

Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

### CODE REVIEW

**Comment by unixsurfer** [comment]
I followed the build instructions and upon installation, I see that python3-daemon and python3-lockfile packages are being installed, even we don't need those two packages anymore. I searched in the debian directory for possible reference to them but I didn't find any. Do you know why they are pulled down during the installation? Another question, rather silly as I don't know much about python packaging for Debian, why I see python3-anycast-healthchecker and anycast-healthchecker packages? Which one should a user use?

```
sudo apt install ./python3-anycast-healthchecker_0.8.1-1_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python3-anycast-healthchecker' instead of './python3-anycast-healthchecker_0.8.1-1_all.deb'
The following packages were automatically installed and are no longer required:
   linux-image-4.9.0-4-amd64 (4.9.65-3+deb9u1)
   linux-perf-4.9 (4.9.65-3+deb9u2)
   rsync (3.1.2-1+deb9u1)
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
   docutils-common (0.13.1+dfsg-2)
   python3-daemon (2.1.2-1)
   python3-docopt (0.6.2-1)
   python3-docutils (0.13.1+dfsg-2)
   python3-lockfile (1:0.12.2-2)
   python3-pygments (2.2.0+dfsg-1)
   python3-roman (2.0.0-2)
Suggested packages:
   docutils-doc (0.13.1+dfsg-2)
   texlive-lang-french (2016.20170123-5)
   texlive-latex-base (2016.20170123-5)
   texlive-latex-recommended (2016.20170123-5)
   python-lockfile-doc (1:0.12.2-2)
   ttf-bitstream-vera (1.10-8)
The following NEW packages will be installed:
   docutils-common (0.13.1+dfsg-2)
   python3-anycast-healthchecker (0.8.1-1)
   python3-daemon (2.1.2-1)
   python3-docopt (0.6.2-1)
   python3-docutils (0.13.1+dfsg-2)
   python3-lockfile (1:0.12.2-2)
   python3-pygments (2.2.0+dfsg-1)
   python3-roman (2.0.0-2)
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 1227 kB/1249 kB of archives.
After this operation, 6059 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by unixsurfer** [comment]
I removed the dependency with 904720cf87d7ae0fd92ab718ea76da119a498497.
But, we don't depend on python-json-logger, which is required when the user enables json logging.
Can you package that module as well? Without it the package is incomplete.

**Comment by BarbarossaTM** [comment]
Hi @unixsurfer 

thanks for testing and your comments! :-)

I started fiddling with packaging quite a while ago, had to preempt my anycast projects and didn't notice, that the dependency has been dropped. Thanks for dropping those.

The user should install `anycast-healthchecker`which will pull `python3-anycast-healthchecker`in. The first one contains the main programm, the service, configuration etc. the latter the python libraries. I have no strong feelings about splitting this into two packages, it could be easily put into one.

About python-json-logger: I noticed the new dependency and already built Debian packaging for this, too. See https://github.com/madzak/python-json-logger/pull/57

I did not specify python3-jsonlogger as a dependency as it isn't available as an official Debian package for now. So people who want to use the Debian packaging for anycast-healthchecker have the option to build a package for the jsonlogger theirselves or use pip to install it.

I'm thinking about maintaining both packages for Debian officially as I'm using anycast at work and for Freifunk, though.

Best
Max

**Comment by ge-fa** [comment]
@BarbarossaTM I'm interested in getting this into Debian as well, and would like to / offer co-maintaining. I would propose to create a repo on salsa.d.o as that is the usual place to do the Debian packaging. debian/ should not really be part of the upstream repo. Appreciate any feedback, and thanks for your work, as well.

**Pull request merged**
